name: nepali_calendar
description: "A Flutter package for Nepali Calendar implementation, providing date conversion, formatting, and calendar widgets with Nepali language support"
version: 0.0.1
homepage:

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  nepali_utils: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
